
if (min(nPreC2D)==1)
{
  cat("###################################################################################\n")
  cat("######################### C2D A LIRE SVP ###########################################\n")
  cat("Ce menu permet de gérer des pré-traitements pour des étapes de Cartino2D\n")
  cat("Il peut être destabilisant de savoir quand les utiliser!\n")
  cat("L'ensemble des paramètres sont définis dans votre fichier de paramétrage.\n")
  cat("Veuillez lire en détail les description de chacun de l'opération que vous souhaityez avant de l'utiliser.\n")
  cat("\n")
  cat("Dans le processus de Cartino2D, plusieurs niveaux de calculs peuvent être menés en fonction des besoins et données disponibles.\n")
  cat("a/ Préliminaires  - P (Ex: Maillage 25m)\n")
  cat("b/ Intermédiaires - I (Ex: Calcul 5m)\n")
  cat("c/ Fins           - F(Ex: Destructuré)\n")
  cat("Pour les explications du menu, les lettre P-I-F seront utilisées pour dire quel processus nécessite quelle étape.\n")
  cat("\n")
}
if (nPreC2D[1]==1)
{
  cat("1. Chargement des bases de données, Tables d'assemblage\n")
  cat("P\n")
  cat("Le travail de récupération des bases de données est plutôt en début de travail.\n")
  cat("Il est aussi possible de créer des tables d'assemblage de dalles Raster à partir des coordonnées sur le nom utilisable à différents moments de la procédure\n")
  cat("\n")
}
if (nPreC2D[2]==1)
{
  cat("2. Sectorisation (souvent après un 1er calcul C2D préliminaire Ex:25m): Redécoupage en plus petits secteurs de calculs (sous-bassins Pluie/Débit)\n")
  cat("I\n")
  cat("Ce travail intervient souvent après un premier calcul de Cartino2D P et donc avant un calcul C2D I\n")
  cat("Il permet de sectoriser pour un futur calcul plus fin en zone de débits/pluies/endoréismes à travers la procédure suivante\n")
  cat("Dans le détail,\n")
  cat("2.1. Zone Débit, Pluie et Endoréique (Post C2D 25m Déluge) et Sectorisation Debit\n")
  cat("Cette étape analyse les résultats d'un C2D P pour définir des zones flash, cours d'eau\n")
  cat("Les zones de débits sont directement finalisées, cependant, si vous voulez utiliser SHYREG débit pour le suite, il faut vérifier que votre zone ne comporte pas trop d'endorésimes.\n")
  cat("Cette étape fournit aussi une couche vecteur des endoréismes.\n")
  cat("Cette couche est à vérifier avant l'étape 2.3, nous conseillons l'utilisation d'OHFlash https://github.com/CEREMA/OHFlash.\n")
  cat("2.2. Zones Potentielles de Ponts (ZPP)\n")
  cat("Cette étape attaque des bases de données (chargées en 1), en particulier la BDTopo de l'IGN pour détecter les zones potentielles de ponts.\n")
  cat("Sur la BDTopo, le principe est simple, trouver les infrastructures (Eau/Route/Voie ferrée) qui se croisent avec des positions différentes par rapport au sol.\n")
  cat("Pour les autres, ce sont plutôt des tampons\n")
  cat("Une vérification visuelle est bienvenue et vous pouvez modifier le fichier créé.\n")
  cat("2.3. Modifs MNT trous points bas endoréismes et/ou creusement ZPP\n")
  cat("Cette étape consiste à\n")
  cat("- trouer le MNT aux points bas des endoréismes\n")
  cat("- baisser le MNT au niveau des ZPP pour permettre un meilleur calcul des bassins versants à l'étape suivante\n")
  cat("2.4. Calcul des bassins versants\n")
  cat("Cette étape consiste à générer des bassins versants de différentes surfaces associés à des réseaux de drainage\n")
  cat("Si vous avez des endoréismes, le réseau de drainage va s'arrêter dans chacun!\n")
  cat("Les directions d'écoulement de cette étape peuvent permettre un rejeu de SHYREG Débit.\n")
  cat("2.5. Sectorisation Pluie\n")
  cat("Cette étape consiste à associée les zones flash (2.1) avec les mini-bassins (2.4) pour créer automatiquement les nouveaux secteurs de Cartino2D I\n")
  cat("Une vérification visuelle est plus que bienvenue\n")
  cat("\n")
}
if (nPreC2D[3]==1)
{
  cat("3. Paramétrages (Strickler et CN spatialisés\n")
  cat("P-I-F\n")
  cat("Cette étape consiste à réaliser des rasters de Strickler ou CN à partir de l'occupation du sol\n")
  cat("Le paramétrage de cette étape se fait à partir de la variable nomXLS\n")
  cat("Le nom de votre fichier est:", nomXLS,"\n")
  cat("Veuillez vous référer à des exemples\n")
  cat(("Ce fichier permet de gérer en entrée des données vectorielles sous forme de polygones ou de lignes.\n"))
  cat("\n")
}
if (nPreC2D[4]==1)
{
  cat("4. Forçages (Pluies ou Débits)\n")
  cat("P-I-F\n")
  cat("4.1. PLUIE mesurée RADAR\n")
  cat("I-F\n")
  cat("Cette étape permet de récupérer des données de Pluie radar mesurées.\n")
  cat("Nabil, s'il y a besoin de plus!\n")
  cat("4.2. EN CONSTRUCTION PLUIE AFAIRE mesurée PLUVIO\n")
  cat("I-F\n")
  cat("4.3. PLUIE statistique (SHYREG INRAE)\n")
  cat("P-I-F\n")
  cat("Cette étape permet de créer des hyétogrammes de Pluie monofréquence spatialisés\n")
  cat("Pour chaque secteur; ils vont se créer dans le dossier:\n")
  cat(dsnPluie," suivi du NOMPOST et du nom de votre secteur\n")
  cat("4.4. AFAIRE DEBITS mesurés\n")
  cat("I-F\n")
  cat("4.5. EN CONSTRUCTION DEBITS statistiques (SHYREG)\n")
  cat("P-I-F\n")
  cat("\n")
}

if (nPreC2D[5]==1)
{
  cat("5. EN CONSTRUCTION References (Bascule de données externes en format utilisables dans C2D)\n")
  cat("P-I-F\n")
  cat("Cette étape a pour objectif de basculer de format divers et variés dans un format exploitable dans Cartino2D pour par exemple la comparaison de débits mesurés sur des sections de contrôle.\n")
  cat("Nabil, s'il y a besoin de plus!\n")
  cat("\n")
}
if (nPreC2D[6]==1)
{
  cat("6. VersionBeta Emprise ZI pour maillage fin / Alea (souvent après 2ème calcul C2D intermédiaire Ex:5m) - simplification, décrénelage...\n")
  cat("P-I-F\n")
  cat("Cette étape permet de calculer une emprise de zone inondable à partir d'un seuil sur HWH ou HSF\n")
  cat("La donnée raster peut être bufférisée de manière positive et négative pour commencer à lisser le résultat\n")
  cat("Elle est convertie en donnée vecteur qui peut être decrenelée.\n")
  cat("Cette option peut être utilisée pour préparer la zone dite 'Exzeco' pour un maillage fin.\n")
  cat("Cette option (très légèrement modifiée) a permis/peut/permettra d'établir les couches d'aléa type PPRi.\n")
  cat("\n")
}
if (nPreC2D[7]==1)
{
  cat("7. EN CONSTRUCTION Création sections de controle (Croisement Couche Points/Emprise ZI) - A controler MANUELLEMENT - OH flash\n")
  cat("P-I\n")
  cat("Cette option permet de créer des sections de contrôle à partir d'une localisation ponctuelle (Stations Vigicrues) et d'un résultat C2D plutôt maximaliste.\n")
}
if (min(nPreC2D)==1)
{
  cat("######################### Fin C2D A LIRE ###########################################\n")
}